### ISSUE TITLE
[BP][CS/CZ] Using wrong "_ragdoll.txt" file with cl_minmodels 1

### ISSUE THREAD

**Issue by di57inct** [hzqst/MetaHookSv#166]
https://user-images.githubusercontent.com/3608544/175117328-17fa3a4f-0633-4bbc-bbcb-ac5aefaff183.mp4

**Comment by hzqst** [comment]
I have no idea what cl_minmodels does, do you know anything about that cvar?

**Comment by hzqst** [comment]
Should have been fixed in 292c29e964a530a909abbdc5768c16a388fd0211, but not tested yet.

**Comment by di57inct** [comment]
Not fixed:

https://user-images.githubusercontent.com/3608544/175699715-a0d4e4a5-c0ab-42de-99da-405e0759d90e.mp4

**Comment by hzqst** [comment]
Should have been fixed in 890d92ef45da0dc811662d4570f8c5e35602d2d4.
