### ISSUE TITLE
[CaptionMod] Chat UI being drawn under other UIs until clicked on

### ISSUE THREAD

**Issue by di57inct** [hzqst/MetaHookSv#169]
https://user-images.githubusercontent.com/3608544/177643578-683a95ee-f87a-4f19-86af-a717795e7b7e.mp4

**Comment by hzqst** [comment]
Should have been fixed in 0c239eaa6b1cf6e8effb692a8c9245a091543321

**Comment by di57inct** [comment]
Tested. Not fixed:

![image](https://user-images.githubusercontent.com/3608544/178038402-2803216d-d8ca-4cb2-a550-61f6054c714d.png)

**Comment by hzqst** [comment]
fixed in a69ec936708d622e1f6f70a7286fe32b67826dc5

**Comment by di57inct** [comment]
Still not fixed:

https://user-images.githubusercontent.com/3608544/178153255-5fce9749-0298-4900-aa8d-33319b479a65.mp4

**Comment by hzqst** [comment]
CounterStrikeViewport (or the Spectator mode overlay) will be brought to front and will be on top of ChatDialog when player starts spectator mode. and there is no way to make the ChatDialog topmost.

**Comment by di57inct** [comment]
Got it. Thank you.
