### ISSUE TITLE
[CaptionMod] Chat input does not close if clicked on history before going into game main menu

### ISSUE THREAD

**Issue by di57inct** [hzqst/MetaHookSv#170]
It only closes if input box is selected.

https://user-images.githubusercontent.com/3608544/177643578-683a95ee-f87a-4f19-86af-a717795e7b7e.mp4

**Comment by hzqst** [comment]
I changed the behavior of GameUI to make it more "Source". GameUI menu don't show up when chat dialog is closed by pressing ESC now in the commit ea95535b2c39711b5e039caad110690e141161e1.

**Comment by di57inct** [comment]
I meant it should close when you go into the game main menu via ESC(cancelselect) key no matter if history or input is selected/clicked. Now you can't go into the game main menu if input is not selected.

**Comment by di57inct** [comment]
Also, the following bug is present now because of this: menu options sometimes don't work anymore.

https://user-images.githubusercontent.com/3608544/178068084-590b4706-cec3-4bd8-9b98-c5912dd089db.mp4

**Comment by hzqst** [comment]
fixed in a69ec936708d622e1f6f70a7286fe32b67826dc5

**Comment by di57inct** [comment]
Still not fixed. It also happened to remain open after changing levels.

https://user-images.githubusercontent.com/3608544/178153113-f87c5e79-555e-4cff-bc12-62caf2eb5aae.mp4
