### ISSUE TITLE
[CM] Persistent messages in some cases

### ISSUE THREAD

**Issue by di57inct** [hzqst/MetaHookSv#199]
No idea what triggers the bug, probably wrong duration identification. Reconnecting/starting a new map fixes the bug.
Dictionary entries can be found at: https://github.com/hzqst/MetaHookSv/issues/188

https://user-images.githubusercontent.com/3608544/189216029-722c1d1d-b663-4877-acd5-b3d2d77ae477.mp4

**Comment by hzqst** [comment]
what bug?

**Comment by di57inct** [comment]
Permanent CaptionMod messages.

**Comment by hzqst** [comment]
Probably because you just connected to a server with `sv.time`(server living time) smaller than the previous joined server, in that case the subtitle lines that spawned from the previous server will not retire until `cl.time`(current client time) > the previous server's  `sv.time`.
This is because the retirement of subtitles relies on `cl.time` (current client time), and client time relies on `sv.time` (server time).

**Comment by hzqst** [comment]
A practical mitigation is to clear all existing subtitles on connecting

**Comment by di57inct** [comment]
As far as i remember i reconnected to the same server via retry command.

**Comment by hzqst** [comment]
> As far as i remember i reconnected to the same server via retry command.

Should have been fixed in https://github.com/hzqst/MetaHookSv/releases/tag/v202209092

Subtitles are cleared when connect to a new server or retry

**Comment by di57inct** [comment]
Will try as soon as i get the chance. Needs a bunch of testing since it doesn't always happen. Will come back with a reply when i get to a conclusion.

**Comment by di57inct** [comment]
Not fixed. Server changed map, messages remained.

https://user-images.githubusercontent.com/3608544/189477800-e2f489f5-7fa8-4684-8f0f-1ac76776e69d.mp4

**Comment by hzqst** [comment]
Probably because [I forgot to call VidInit for SubtitlePanel](https://github.com/hzqst/MetaHookSv/commit/bcc6acf4fc4546605bec9851e73d0b98e5a4c3d5)
Should have been fixed in https://github.com/hzqst/MetaHookSv/releases/tag/v20200910

**Comment by di57inct** [comment]
Problem still present with latest version. Happened after server map change.

**Comment by di57inct** [comment]
Closing this as fixed via https://github.com/hzqst/MetaHookSv/releases/tag/v20230314a until proven otherwise and reopening later if necessary.
