### ISSUE TITLE
[BP] Ragdolls reset to static corpse

### ISSUE THREAD

**Issue by di57inct** [hzqst/MetaHookSv#364]
> |index|api|             plugin name|          plugin version|
> |    0| v2|   Gmcx_model_effect.dll|                        |
> |    1| v4|        StudioEvents.dll|     2024-01-15T14:12:58|
> |    2| v4|  BulletPhysics_AVX2.dll|     2024-01-15T14:12:13|
> |    3| v4|       Renderer_AVX2.dll|     2024-01-15T14:08:40|
> |    4| v4|          CaptionMod.dll|     2024-01-15T14:12:21|

In remote server, if the ragdoll is active and the player looks away, it resets to a static corpse.
It does not happen if ragdoll is in sleep mode when the player looks away.
Happens to both bots and players.
https://www.youtube.com/watch?v=__aucKhkgxE

In listenserver(new game) it doesn't happen at all(although notice in the start of the second video that when the player killed a bot out of my view it turned into a static corpse directly; this is not really an issue though).
https://www.youtube.com/watch?v=zR2WfZXlcS8 - bots
https://www.youtube.com/watch?v=fhtQECv6BbI&t=39 - connected player

Also happens to hostage entities but you have to move further away in order for them to reset to static corpses(tested on listenserver).
https://www.youtube.com/watch?v=CidoNi17qoQ

Player ragdoll file(leet_ragdoll.txt - cs hd models):
```
[DeathAnim]
101 99
102 31
103 72
104 14
105 142
106 155
107 14
108 139
109 21
110 16

[RigidBody]
Head 7  6   capsule  -5   5.0   0.1   3
Spine 5  4   capsule  -2   8.0   0.1   10
Pelvis 1  2  capsule  2   7.5   0.1   10

LArm 9 10  capsule  5  2.5   8.0    2
LArm2 10 11  capsule  6   2.5   10.0    2

RArm 18 19  capsule  5   2.5   8.0    2
RArm2 19 20  capsule  6   2.5   10.0    2

LLeg 26 27  capsule  10   3.6   10.0    2
LLeg2 27 28  capsule  8   3.0   8.0    2

RLeg 30 31  capsule  10   3.6   10.0    2
RLeg2 31 32  capsule  8   3.0   8.0    2

[Constraint]
Spine  Head   conetwist 6 7   0 0 0     0  5  0        0.01  0.01  0.2
Pelvis Spine  conetwist 1 5    0 0 0     0 8  0        0.1  0.1  0.1

Spine  LArm   conetwist 8 9    0 0 0     0 -6.5  0        0.2 0.2 0.2
LArm   LArm2  conetwist 9 10    0 0 0     0 -6  0       0.2 0.2 0.1

Spine  RArm   conetwist 16 17    0 0 0     0 -6.5  0        0.2 0.2 0.2
RArm   RArm2  conetwist 17 18    0 0 0     0 -6  0        0.2 0.2 0.1

Pelvis LLeg   conetwist 24 24  0 0 0     0 -7  0        0.1  0.1  0.25
LLeg2  LLeg   hinge     25 25  0 0 0     0 8 0         -0.2  0.0  0

Pelvis RLeg   conetwist 29 29  0 0 0     0 -7  0        0.1  0.1  0.25
RLeg2  RLeg   hinge     30 30  0 0 0     0 8 0         -0.2  0.0  0

[WaterControl]
Head    0  0  0    1.03  0.5  0
Spine   0  0  0    1.03  0.5  0
Pelvis  0  0  0    1.03  0.5  0

LArm    0  0  0    1.03  0.5  0
LArm2   0  0  0    1.03  0.5  0

RArm    0  0  0    1.03  0.5  0
RArm2   0  0  0    1.03  0.5  0

LLeg    0  0  0    1.03	0.5  0
LLeg2   0  0  0    1.03	0.5  0

RLeg    0  0  0    1.03	0.5  0
RLeg2   0  0  0    1.03	0.5  0
```

Hostage entity ragdoll file(hostage_ragdoll.txt - cs classic model):
```
[DeathAnim]
12 0

[RigidBody]
Head   12  11  sphere  -4.0  5.0  0.0   6
Spine  10   11  capsule  1.0  8.0  3.0   10
Pelvis 1   10  capsule  3.0  6.0  2.0   10

LArm   14   15 capsule  5.0  2.2  8.0   3
LArm2  15  16 capsule  5.0  2.2  8.0   3
LHand  16  15 capsule -2.0  1.8  2.0   1

RArm   18  19 capsule  5.0  2.2  8.0   3
RArm2  19  20 capsule  5.0  2.2  8.0   3
RHand  20  19 capsule -2.0  1.8  2.0   1

LLeg   2  3 capsule  8.0  3.6  14.0  4
LLeg2  3  4 capsule  10.0 3.3  18.0  4

RLeg   5  6 capsule  8.0  3.6  14.0  4
RLeg2  6  7 capsule  10.0 3.3  18.0  4

[Constraint]
Spine  Head   conetwist 11  12   0 0 0    0 -3 0    0.0  0.0  0.2
Pelvis Spine  conetwist 10  11    0 0 0   -3 -9 0    0.0  0.0  0.05

Spine  LArm   conetwist 13  14    0 0 0    0 -4  0   0.33 0.33 1.0
LArm   LArm2  conetwist 14  15   0 0 0    0 -4  0   0.2  0.2  0.2
LArm2  LHand  conetwist 15 16   0 0 0    0  3  0   0.2  0.2  0.3

Spine  RArm   conetwist 17  18   0 0 0    0 -4  0   0.33 0.33 1.0
RArm   RArm2  conetwist 18 19   0 0 0    0 -4  0   0.2  0.2  0.2
RArm2  RHand  conetwist 19 20   0 0 0    0  3  0   0.2  0.2  0.3

Pelvis LLeg   conetwist 2 2  0 0 0     0 -9  0   0.2  0.2  0.25
LLeg2  LLeg   hinge     2 2  0 0 0     0 8 0    -0.5  0.0  0

Pelvis RLeg   conetwist 5 5  0 0 0     0 -9  0   0.2  0.2  0.25
RLeg2  RLeg   hinge     5 5  0 0 0     0 8 0    -0.5  0.0  0

[WaterControl]
Head    0  0  0    1.01  0.5  0
Spine   0  0  0    1.01  0.5  0
Pelvis  0  0  0    1.01  0.5  0

LArm    0  0  0    1.01  0.5  0
LArm2   0  0  0    1.01  0.5  0

RArm    0  0  0    1.01  0.5  0
RArm2   0  0  0    1.01  0.5  0

LLeg    0  0  0    0.475 0.5  0
LLeg    8  0  0    0.475 0.5  0
LLeg2   0  0  0    0.475 0.5  0
LLeg2   10 0  0    0.475 0.5  0

RLeg    0  0  0    0.475 0.5  0
RLeg    8  0  0    0.475 0.5  0
RLeg2   0  0  0    0.475 0.5  0
RLeg2   10 0  0    0.475 0.5  0
```

**Comment by hzqst** [comment]
Should've been fixed in https://github.com/hzqst/MetaHookSv/releases/tag/v20240116a

**Comment by di57inct** [comment]
Confirming fixes, thank you ❤️

**Comment by GradersPro88** [comment]
> Should've been fixed in https://github.com/hzqst/MetaHookSv/releases/tag/v20240116a

![image](https://github.com/hzqst/MetaHookSv/assets/89559444/797c3965-8745-4212-8689-d9008246d605)
@hzqst still persists on day of defeat

**Comment by hzqst** [comment]
> > Should've been fixed in https://github.com/hzqst/MetaHookSv/releases/tag/v20240116a
> 
> ![image](https://private-user-images.githubusercontent.com/89559444/303982032-797c3965-8745-4212-8689-d9008246d605.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDg0ODczNDksIm5iZiI6MTcwODQ4NzA0OSwicGF0aCI6Ii84OTU1OTQ0NC8zMDM5ODIwMzItNzk3YzM5NjUtODc0NS00MjEyLTg2ODktZDkwMDgyNDZkNjA1LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAyMjElMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMjIxVDAzNDQwOVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTlhNWRlNzc0YTUwYmNmODRiMWEwNzcwM2Y4OTI2YjI3YTAxODU0NmZiZDQ1MWIwNjQ2MmYwNmU0MTZjYTc3ZDUmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.AZWRvXxAiYG2frLbPVHLOIVV505y8_q6qo2xQTWpRis) @hzqst still persists on day of defeat

Can you upload the corresponding _ragdoll.txt ?

**Comment by GradersPro88** [comment]
> > > Should've been fixed in https://github.com/hzqst/MetaHookSv/releases/tag/v20240116a
> > 
> > 
> > ![image](https://private-user-images.githubusercontent.com/89559444/303982032-797c3965-8745-4212-8689-d9008246d605.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDg0ODczNDksIm5iZiI6MTcwODQ4NzA0OSwicGF0aCI6Ii84OTU1OTQ0NC8zMDM5ODIwMzItNzk3YzM5NjUtODc0NS00MjEyLTg2ODktZDkwMDgyNDZkNjA1LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAyMjElMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMjIxVDAzNDQwOVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTlhNWRlNzc0YTUwYmNmODRiMWEwNzcwM2Y4OTI2YjI3YTAxODU0NmZiZDQ1MWIwNjQ2MmYwNmU0MTZjYTc3ZDUmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.AZWRvXxAiYG2frLbPVHLOIVV505y8_q6qo2xQTWpRis) @hzqst still persists on day of defeat
> 
> Can you upload the corresponding _ragdoll.txt ?

sure:
[axis-inf_ragdoll.txt](https://github.com/hzqst/MetaHookSv/files/14368162/axis-inf_ragdoll.txt)

**Comment by caoqt1** [comment]
Seems to be more egregious on the newest version. Ragdolls will spawn when I kill someone on Counter Strike, but after a couple seconds, the ragdoll will totally disappear and be replaced with the usual corpse. Before, touching the corpse would kick it out of sleep and turn it into a ragdoll, but now its inconsistent as sometimes it doesn't reactivate physics

**Comment by hzqst** [comment]
Fixed in https://github.com/hzqst/MetaHookSv/releases/tag/v20241208b

**Comment by hzqst** [comment]
> > > > Should've been fixed in https://github.com/hzqst/MetaHookSv/releases/tag/v20240116a
> > > 
> > > 
> > > ![image](https://private-user-images.githubusercontent.com/89559444/303982032-797c3965-8745-4212-8689-d9008246d605.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDg0ODczNDksIm5iZiI6MTcwODQ4NzA0OSwicGF0aCI6Ii84OTU1OTQ0NC8zMDM5ODIwMzItNzk3YzM5NjUtODc0NS00MjEyLTg2ODktZDkwMDgyNDZkNjA1LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAyMjElMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMjIxVDAzNDQwOVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTlhNWRlNzc0YTUwYmNmODRiMWEwNzcwM2Y4OTI2YjI3YTAxODU0NmZiZDQ1MWIwNjQ2MmYwNmU0MTZjYTc3ZDUmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.AZWRvXxAiYG2frLbPVHLOIVV505y8_q6qo2xQTWpRis) @hzqst still persists on day of defeat
> > 
> > 
> > Can you upload the corresponding _ragdoll.txt ?
> 
> sure: [axis-inf_ragdoll.txt](https://github.com/hzqst/MetaHookSv/files/14368162/axis-inf_ragdoll.txt)

Fixed in https://github.com/hzqst/MetaHookSv/releases/tag/v20241208b

**Comment by di57inct** [comment]
Unable to confirm fix. Ragdolls now trigger only after ClCorpse message and being touched:
https://youtu.be/AuASaxQrsLg

> ] mh_pluginlist 
> |index|api|             plugin name|          plugin version|
> |    0| v2|   Gmcx_model_effect.dll|                        |
> |    1| v4|    ResourceReplacer.dll|     2024-12-09T12:39:06|
> |    2| v4|           HeapPatch.dll|     2024-12-09T12:39:11|
> |    3| v4|         ThreadGuard.dll|     2024-12-09T12:38:57|
> |    4| v4|     PrecacheManager.dll|     2024-12-09T12:38:00|
> |    5| v4|        StudioEvents.dll|     2024-12-09T12:38:54|
> |    6| v4|  BulletPhysics_AVX2.dll|     2024-12-09T12:36:44|
> |    7| v4|       Renderer_AVX2.dll|     2024-10-14T12:14:24|
> |    8| v4|          CaptionMod.dll|     2024-12-09T12:37:36|
> |    9| v4|      VGUI2Extension.dll|     2024-12-09T12:37:13|
