### ISSUE TITLE
Latest MetahookSV Ragdoll problems...

### ISSUE THREAD

**Issue by junevillarreal** [hzqst/MetaHookSv#492]
Hello, I've tried the last updated version, but it seem the ragdoll won't work properly.. The ragdoll only works when the model already "dead", even if i alrd set every dead sequence to 0 in ragdoll.txt. So when the model died, they play the default anims, and when they're already on the ground, the ragdoll just activated

https://github.com/user-attachments/assets/a51e8484-df57-44e6-86fa-7477702be27b

**Comment by hzqst** [comment]
The animation control system of Ragdoll Object is still W.I.P. please wait for next update.

**Comment by di57inct** [comment]
Most probably related: check the code for frame count of ragdoll trigger as i strongly believe it's not correct.

**Comment by hzqst** [comment]
Can you try https://github.com/hzqst/MetaHookSv/releases/tag/v20240930a ?

**Comment by junevillarreal** [comment]
I think it's still not fixed yet, I tried it, yet it still behave like in this vid

**Comment by hzqst** [comment]
Should have been fixed in https://github.com/hzqst/MetaHookSv/releases/tag/v20241007a

**Comment by junevillarreal** [comment]
I don't know man.. I think it's not fixed yet, I tried the latest ver, and the ragdoll remains act like the video in this issues. And I also tried the version you mentioned here, it seems the ragdoll not working at all

**Comment by hzqst** [comment]
How can I repro the issue on my end?

**Comment by caoqt1** [comment]
@hzqst Not sure if related, but it seems to have gotten more egregious on the newest version. Ragdolls will spawn when I kill someone on Counter Strike, but after a couple seconds, the ragdoll will totally disappear and be replaced with the usual corpse. Before, touching the corpse would kick it out of sleep and turn it into a ragdoll, but now its inconsistent as sometimes it doesn't reactivate physics

**Comment by caoqt1** [comment]
Tested some more:
Using latest release on the HL25 build will result in the opposite of this issue, where the player will ragdoll when died, but after a small amount of time, will be replaced with the static corpse.
On the blob version (steam_legacy), players will die with static corpse, and after animation finishes, the ragdoll will kick in, similar to this issue.

**Comment by hzqst** [comment]
> @hzqst Not sure if related, but it seems to have gotten more egregious on the newest version. Ragdolls will spawn when I kill someone on Counter Strike, but after a couple seconds, the ragdoll will totally disappear and be replaced with the usual corpse. Before, touching the corpse would kick it out of sleep and turn it into a ragdoll, but now its inconsistent as sometimes it doesn't reactivate physics

Fixed in https://github.com/hzqst/MetaHookSv/releases/tag/v20241208b
