### ISSUE TITLE
[v20250207] Crash when launching CS/CZ(both latest & 8684)

### ISSUE THREAD

**Issue by di57inct** [hzqst/MetaHookSv#535]
Only build 8684 generates dump files for some reason.

[dumps.zip](https://github.com/user-attachments/files/18709544/dumps.zip)

**Comment by hzqst** [comment]
Fixed in https://github.com/hzqst/MetaHookSv/releases/tag/v20250208a

**Comment by di57inct** [comment]
Still crashes on [v20250209a](https://github.com/hzqst/MetaHookSv/releases/tag/v20250209a)
CS crashed when entering server(82.77.209.13:27015 if u wanna test), CZ crashes directly on startup.

[dumps.zip](https://github.com/user-attachments/files/18725760/dumps.zip)

**Comment by hzqst** [comment]
> Still crashes on [v20250209a](https://github.com/hzqst/MetaHookSv/releases/tag/v20250209a) CS crashed when entering server(82.77.209.13:27015 if u wanna test), CZ crashes directly on startup.
> 
> [dumps.zip](https://github.com/user-attachments/files/18725760/dumps.zip)

Fixed in https://github.com/hzqst/MetaHookSv/releases/tag/v20250210b

**Comment by di57inct** [comment]
Confirming fix, ty <3
